global:
  name: consul
connectInject:
  enabled: true
controller:
  enabled: true
server:
  updatePartition: 3
  nodeSelector: |
    aksVersion: v1.20.15
ui:
  enabled: true
  service:
    type: LoadBalancer